### ISSUE TITLE
issue with post tags

### ISSUE THREAD

**Issue by z9fr** [z9fr/blog-backend#5]
there's a bug/ issue with how posts and tags relationship works. it seems like its only fetching the first tag ( if im not mistaken ) need to fix this issue soon.

also there seems to like some issue with the tag relationship since its creating a new tag every-time im adding a tag when creating a post. it should only create a new tag if its not taken

![image](https://user-images.githubusercontent.com/66930150/161615936-f0b272d5-c23c-43d2-8cb4-627acb125d8d.png)

**Comment by ebadfd** [comment]
fixed https://github.com/z9fr/blog-backend/commit/1a676eb65919a55d2d1cdca72d9c46842e60f6fa
